### ISSUE TITLE
Remove/Revoke AMO API credentials

### ISSUE THREAD

**Issue by wagnerand** [Shadowvail/FireFoxPlugin#1]
You should never share your AMO API credentials. Anyone that has them can upload new versions of your add-on on your behalf.

You need to:
- At the very least revoke the AMO API credentials on https://addons.mozilla.org/en-US/developers/addon/api/key/ _immediately_
- Remove the file or the credentials in it and never ever store it in a remote repository again.

**Comment by Shadowvail** [comment]
Hey thanks for the comment. I guess my gitignore file wasn't being read and uploaded that txt document by accident. This is a completely non-serious repository though with an entirely separate mozilla developer account than my normal one, so no security concerns. Thank you for the heads up though!
